package m2t.util;

import java.text.SimpleDateFormat;
import java.util.Date;

/**
 * A utility class with methods that may be used in the Xpand templates.
 * 
 * Usage:
 *  Add «EXTENSION template::util::util» at the top of your template file
 *  All static methods are now available by using «method()» in the template
 * 
 * @author markov
 */
public final class TemplateUtils
{
	private static String appIdentifier;
	private static String appPackageName;
	
	/**
	 * @return a string representatin on the current local date
	 */
	public static String timestamp()
	{
		return new SimpleDateFormat("dd-MM-yyyy HH:mm:ss").format(new Date());
	}
	
	/**
	 * @return a string to put before a class
	 */
	public static String classHeader(String className)
	{
		return "/**\n" +
				"* This class was generated by the Sigmax Modeling Project.\n" +
				"*\n" +
				"* @date " + timestamp() + "\n" +
				"* @generated\n" +
				"*/";
	}
	
	public static void setAppIdentifier(String s)
	{
		appIdentifier = s;
	}
	
	public static String getAppIdentifier()
	{
		return appIdentifier;
	}
	
	public static void setPackageName(String s)
	{
		appPackageName = s;
	}
	
	public static String getPackageName()
	{
		return appPackageName;
	}
	
	public static String getPackageDir()
	{
		return appPackageName.replace('.', '/');
	}
}